name: Compile esp.cpp on Windows

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MSVC
        run: |
          # Set environment variables for MSVC
          echo 'Setting up MSVC environment...'
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat"

      - name: Build esp.cpp
        run: |
          cd CS2-Glow
          cl /EHsc esp.cpp
