name: Compile esp.cpp on Windows

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MSVC compiler
        uses: actions/setup-msvc@v1

      - name: Build esp.cpp
        run: |
          cd CS2-Glow
          cl /EHsc esp.cpp
